# Generated by Django 2.2.3 on 2019-07-19 01:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_serial_number', models.CharField(max_length=5)),
                ('container_description', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modify_by', models.CharField(max_length=20)),
                ('modify_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generals.Warehouse')),
            ],
            options={
                'verbose_name_plural': 'Containers',
            },
        ),
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_serial_number', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generals.DocumentType')),
            ],
            options={
                'verbose_name_plural': 'Order Headers',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=20, null=True)),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recordmgnts.Container')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordmgnts.OrderHeader')),
            ],
            options={
                'verbose_name_plural': 'Order Details',
            },
        ),
    ]
