# Generated by Django 2.2.3 on 2019-07-08 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_serial_number', models.CharField(max_length=5)),
                ('container_description', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 8, 10, 59, 23, 71000))),
                ('modify_by', models.CharField(max_length=20)),
                ('modify_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 8, 10, 59, 23, 71000))),
            ],
            options={
                'verbose_name_plural': 'Containers',
            },
        ),
    ]
