# Generated by Django 2.2.3 on 2019-07-09 08:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generals', '0002_auto_20190709_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_serial_number', models.CharField(max_length=5)),
                ('container_description', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modify_by', models.CharField(max_length=20)),
                ('modify_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generals.Warehouse')),
            ],
            options={
                'verbose_name_plural': 'Containers',
            },
        ),
    ]
