# Generated by Django 2.2.3 on 2019-07-09 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='modify_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
