# Generated by Django 2.2.3 on 2019-07-07 14:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_code', models.CharField(max_length=5)),
                ('series_description', models.CharField(max_length=50)),
                ('starting_number', models.IntegerField()),
                ('ending_number', models.IntegerField()),
                ('next_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 7, 22, 17, 19, 582000))),
                ('modify_by', models.CharField(max_length=20)),
                ('modify_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 7, 22, 17, 19, 582000))),
            ],
            options={
                'verbose_name_plural': 'Series_Numbers',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(max_length=5)),
                ('document_description', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 7, 22, 17, 19, 582000))),
                ('modify_by', models.CharField(max_length=20)),
                ('modify_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 7, 22, 17, 19, 582000))),
                ('document_number_seriesId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generals.SeriesNumber')),
            ],
            options={
                'verbose_name_plural': 'Document_Types',
            },
        ),
    ]
