# Generated by Django 2.2.3 on 2019-07-08 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 8, 10, 59, 23, 47000)),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='modify_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 8, 10, 59, 23, 47000)),
        ),
        migrations.AlterField(
            model_name='seriesnumber',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 8, 10, 59, 23, 50000)),
        ),
        migrations.AlterField(
            model_name='seriesnumber',
            name='modify_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 8, 10, 59, 23, 50000)),
        ),
    ]
